export const strings = {
  pt: {
    welcome: 'Bem-vindo',
    chatHistory: 'Histórico de conversas',
    disclaimer: 'O ChatGPT pode cometer erros. Considere verificar informações importantes.',
    loginError: 'Erro no login',
    assistantGreeting: 'Olá, como posso te ajudar?',
    inputPlaceholder: 'Digite aqui...',
    back: 'Voltar',
    workEmail: 'Email corporativo',
    password: 'Senha',
    forgotPassword: 'Se você esqueceu sua senha, entre em contato com a equipe de TI.',
    login: 'Entrar',
    chatbotDescription: 'O chatbot te ajuda com tudo',
  },
  en: {
    welcome: 'Welcome',
    chatHistory: 'Chat history',
    disclaimer: 'ChatGPT may make mistakes. Please verify important information.',
    loginError: 'Login error',
    assistantGreeting: 'Hi, how can I help you?',
    inputPlaceholder: 'Type here...',
    back: 'Back',
    workEmail: 'Work email',
    password: 'Password',
    forgotPassword: 'If you have forgotten your password, please contact the IT team.',
    login: 'Login',
    chatbotDescription: 'The chatbot helps you with everything',
  },
};
